apiVersion: v1
kind: Service
metadata:
  name: schedulers-service
  labels:
    app: notification
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: schedulers