apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-service
  namespace: oldmutual
  labels:
    app: reporting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-service
  template:
    metadata:
      labels:
        app: reporting-service
    spec:
      containers:
        - name: reporting-service
          image: registry.gitlab.com/systechlimited/fm/reporting-service:latest
          imagePullPolicy: Always
          env:
            - name: HIBERNATE_DIALECT
              value: "org.hibernate.dialect.PostgresPlusDialect"
            - name: DATABASE_DRIVER_CLASS
              value: "org.postgresql.Driver"
            - name: CLIENT
              value: "oldmutual"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: reporting-service-secret
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reporting-service-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reporting-service-secret
                  key: DATABASE_PASSWORD
          ports:
            - containerPort: 8081