apiVersion: apps/v1
kind: Deployment
metadata:
  name: xc
  namespace: oldmutual
  labels:
    app: xc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xc
  template:
    metadata:
      name: xc
      labels:
        app: xc
    spec:
      volumes:
        - name: xc-volume
          persistentVolumeClaim:
            claimName: xc-pvc
      containers:
        - name: xc-oldmutual
          image: registry.gitlab.com/systechlimited/fm/xe/xc-oldmutual:latest
          volumeMounts:
            - mountPath: "/opt/jboss/FundMasterGeneralFiles"
              name: xc-volume
            - mountPath: "/opt/jboss/batch-uploads"
              name: xc-volume
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9990
              protocol: TCP
          command: ["/bin/sh", "/opt/jboss/wildfly/configure_wildfly.sh"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: xc-secret
                  key: DATABASE_URL
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: xc-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: xc-secret
                  key: DATABASE_PASSWORD
            - name: WILDFLY_USER
              valueFrom:
                secretKeyRef:
                  name: xc-secret
                  key: WILDFLY_USERNAME
            - name: WILDFLY_PASS
              valueFrom:
                secretKeyRef:
                  name: xc-secret
                  key: WILDFLY_PASSWORD
      restartPolicy: Always
