apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xc-pvc
  namespace: oldmutual
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
