apiVersion: v1
kind: Service
metadata:
  name: reporting-service-service
  labels:
    app: reporting-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: reporting-service