apiVersion: v1
kind: Service
metadata:
  name: schedulers
  namespace: schedulers
  labels:
    app: schedulers
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: schedulers


---
apiVersion: v1
kind: Service
metadata:
  name: schedulers-logs
  namespace: schedulers
  labels:
    app: schedulers
spec:
  type: LoadBalancer
  ports:
    - port: 9990
      targetPort: 9990
  selector:
    app: schedulers