apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: notification