apiVersion: v1
kind: Service
metadata:
  name: mss-application-service
  namespace: oldmutual
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: mss

---

apiVersion: v1
kind: Service
metadata:
  name: mss-management-service
  namespace: oldmutual
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9990
  selector:
    app: mss
