apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-service
  namespace: oldmutual
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 2255
      targetPort: 2255
  selector:
    app: kafka

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-controller-service
  namespace: oldmutual
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 19092
      targetPort: 19092
  selector:
    app: kafka
